### ISSUE TITLE
Inconsistent output of Poseidon CRH between native and constraints

### ISSUE THREAD

**Issue by tsunrise** [arkworks-rs/crypto-primitives#57]
I was helping @mfaghihi debugging the code, and found that the native code and constraints of Poseidon CRH in `crypto-primitives` seem to return different results. 

Here are the tests I wrote: https://github.com/tsunrise/Poseidon/blob/debug/src/test.rs (the test failed)

Is there a bug in the Poseidon CRH implementations, or the Poseidon parameter is not correct?
(Could someone add unit tests for the CRH implementations if they have time? Thanks)

(btw, @mfaghihi 's implementation is using 0.2 release, but I have not changed the implementation of Poseidon CRH since then so I'd assume same problem will happen in 0.3 release)

cc: @drewstone @weikengchen

**Comment by weikengchen** [comment]
Let me first refer @mfaghihi to the ark-sponge implementation of the Poseidon hash function, which I think would also do the work for his project. 

I would not have time this time to do a pass this week. But the Poseidon CRH has not been extensively tested. 

At this moment, I think instead of adding more unit tests to Poseidon CRH, we may better just reconcile Poseidon CRH with the ark-sponge implementations. 

Later, we may need to refactor the TwoToOneCRH trait again. The current TwoToOneCRH requires left and right to be [u8], but it is much better if TwoToOneCRH requires the left and right to be TwoToOneCRH::Output as well.

**Comment by tsunrise** [comment]
make sense to me 🆗

**Comment by weikengchen** [comment]
The current Poseidon CRH implementation has a few nice works that reduce the SBOX cost for common alpha. Our ark-sponge currently uses the generic `pow_by_constant`. 

Later we may go back to this. `pow_by_constant` could be improved via finding the NAF of the number. There are many works ahead to bring ark-sponge in without losing the efficiency of a specialized implementation.

**Comment by mfaghihi** [comment]
> Let me first refer @mfaghihi to the ark-sponge implementation of the Poseidon hash function, which I think would also do the work for his project.
> 
> I would not have time to do a pass this week. But the Poseidon CRH has not been extensively tested.
> 
> At this moment, I think instead of adding more unit tests to Poseidon CRH, we may better just reconcile Poseidon CRH with the ark-sponge implementations.
> 
> Later, we may need to refactor the TwoToOneCRH trait again. The current TwoToOneCRH requires left and right to be [u8], but it is much better if TwoToOneCRH requires the left and right to be TwoToOneCRH::Output as well.

Thank you!
I was going to use the  ark-sponge implementation sine it may be enough for my task. Using permutation-based Poseidon is interesting to do and may be more efficient for some applications

**Comment by drewstone** [comment]
I suppose this may also be fixed in the current PR open for updating the Poseidon implementation.
